export const ADD_NOW_PLAYING = "ADD_NOW_PLAYING";
export const ADD_UPCOMING = "ADD_UPCOMING";
export const RESET_HOME = "RESET_HOME";
export const SET_TMDB_ERROR = "SET_TMDB_ERROR";
export const SET_ADULT_FILTER = "SET_ADULT_FILTER";
