export const API_KEY = process.env.TMDB_KEY;
export const API_URL = `https://api.themoviedb.org/3/`;
export const REQ_TIMEOUT = 30000;
export const IMAGE_URL = `https://image.tmdb.org/t/p`;
export const COVER_URL = `${IMAGE_URL}/original`;
export const IMDB_TITLE = `https://www.imdb.com/title/`;
export const IMDB_NAME_URL = `https://www.imdb.com/name/`;
export const YTS_URL = `https://yts.am/`;
export const GET_TORRENT_URL = `${YTS_URL}api/v2/list_movies.json?query_term=`;
